### ISSUE TITLE
Error on scanning on vps 16gb ram (provider GameHosting)

### ISSUE THREAD

**Issue by Craftc48** [replydev/Quboscanner#3]
java.nio.file.FileSystemException: outputs/137.74.0.0-137.74.255.255.txt: Too many open files
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:91)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
        at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
        at java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:434)
        at java.nio.file.Files.newOutputStream(Files.java:216)
        at java.nio.file.Files.write(Files.java:3292)
        at utils.FileUtils.doAppend(FileUtils.java:24)
        at utils.FileUtils.appendToFile(FileUtils.java:16)
        at qubo.net.Check.check(Check.java:81)
        at qubo.net.Check.run(Check.java:41)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by replydev** [comment]
Please explain when the bug appears

**Comment by Craftc48** [comment]
when the scan starts it creates the txt file with the name of the range but after some server found the error comes out and does not scan. (sorry google traductor)

**Comment by replydev** [comment]
How many servers? Is the number always the same?

**Comment by Craftc48** [comment]
yes, 127.0.0.1-127.0.250.250 (example)

**Comment by replydev** [comment]
I will try to replicate this bug, thank you.


Off-topic: did you know that you can just write:

`127.0.*.*` Or `127.0.0.0/16`

as input range?

**Comment by Craftc48** [comment]
thanks
im fixxed
